name: 'Lint Code'

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          # Run flake8 and stop build on critical errors
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Run style check (exit-zero lets CI pass, but still reports issues)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JSHint
        run: npm install --global jshint

      - name: Run JSHint
        run: |
          # Run JSHint on all JS files (excluding node_modules)
          jshint . --exclude node_modules
